### ISSUE TITLE
No console output with the .exe prevents --help from working

### ISSUE THREAD

**Issue by leandrotlz** [mircokroon/minecraft-world-downloader#115]
**Describe the bug**
Running `java -jar world-downloader.jar --help` (or with invalid parameters) returns a list of valid command line parameters in the console. Running `world-downloader.exe --help` (or with invalid parameters) does no such thing, it just silently quits.

**Steps to reproduce**
Run `.\world-downloader.exe --help` using Cmd or Powershell. No console output will be given.

**Version**
 - Downloader: v1.11.3

**Comment by mircokroon** [comment]
Hmm I'm not sure what to do about this. As far as I know, the way the .exe wrapping works you need to pick between GUI and console, the GUI mode refuses to print anything and the console mode will open a console window even if started by double-clicking it (which seems undesirable).

The way it's set up now, the .jar version is basically better than the .exe (since it supports both), except for the .exe being slightly easier to use for people that are less experienced.

**Comment by mircokroon** [comment]
I'll just clarify this in the readme. 
.exe -> GUI only
.jar -> both GUI and commandline

Technically the .exe supports commandline but as shown here, it doesn't work well.
