### ISSUE TITLE
Reduce memory footprint of overview if RAM usage is too high

### ISSUE THREAD

**Issue by mircokroon** [mircokroon/minecraft-world-downloader#149]
#148

**Comment by maxsupermanhd** [comment]
@mircokroon This is very big issue, can you add button to context menu or hotkey or even in-game command that will trigger force-save to disk? I've lost half of download because of this not long ago. My laptop have only 8GB RAM total and having 4 already dedicated for MC not leaving much space and it is swapping like crazy...

**Comment by mircokroon** [comment]
@maxsupermanhd well it does auto-save every 20 seconds or so regardless, I believe there used to be a bug before the caused some saving issues but I think those are fixed now. 

A lot of of the RAM usage is caused by the GUI and yeah, that should be fixed/improved. It is possible to run the downloader on a different device from the instance of Minecraft but it's a little bit more work with the authentication to get working.
