### ISSUE TITLE
Bug: Doesn't support "plugin" packets

### ISSUE THREAD

**Issue by Gaming32** [mircokroon/minecraft-world-downloader#169]
**Describe the bug**
This software doesn't forward "plugin" packets from/to the server, which makes server-side mods/plugins unable to interact with the client-side versions. A great example is [Plasmo Voice](https://github.com/plasmoapp/plasmo-voice) (which is how I learned that this software doesn't support this.)

**Steps to reproduce**
Install a server-side plugin (like [Plasmo Voice Server](https://www.spigotmc.org/resources/plasmo-voice-server.91064/)), and the client-side version (like [Plasmo Voice Client](https://www.curseforge.com/minecraft/mc-mods/plasmo-voice-client)). Open the client, connect to the server through this software, and press V. It will say that the server doesn't have Plasmo Voice installed, when it in fact does.

**Screenshots**
Connected through this software:
![image](https://user-images.githubusercontent.com/42721887/123158231-225df100-d431-11eb-8e90-8aacdbf032df.png)
Connected directly:
![image](https://user-images.githubusercontent.com/42721887/123158276-31dd3a00-d431-11eb-99da-21235f2f4b32.png)

**Version**
 - Game: Fabric 1.17
 - Downloader: latest
 - Launcher (if login issues): 14.2

**Comment by mircokroon** [comment]
Hmm I don't think the issue is related to forwarding regular packets, I think it's due to Plasmo using a separate UDP connection to transmit the voice over. I'm able to get it to work fine with a local server.

My theory is that when you connect to `remote-server.com` through the downloader, the voice connection should be happening on `remote-server.com:60606` but instead it'll try `localhost:60606`. I'm not sure this can be fixed.

**Comment by Gaming32** [comment]
That's extremely likely correct.
