### ISSUE TITLE
Java version while building and testing

### ISSUE THREAD

**Issue by maxsupermanhd** [mircokroon/minecraft-world-downloader#182]
I was updating my local world downloader repository and was rebuilding it but got this error message while running tests:
```
Cannot run Minecraft version 1.17+ with a Java version below 16. You are currently using Java version 11.
```
I am running `mvn package` with java 11 because it looks like it is not supporting 16 yet, is it true? How can I specify java version for tests? Is it even thing that I should worry about?

**Comment by maxsupermanhd** [comment]
Also because of this error while passing tests it is unable to build jar target file that I actually need.

**Comment by mircokroon** [comment]
I believe the program can be compiled with any version from 8 to 16, so `mvn package` should work with all these. Running the tests fully for the first time requires Java 16. This is because it has to run the `server.jar` from 1.17 which requires Java 16. After the tests have run once it should already have the generated registry files from 1.17 so then it'll actually work with lower versions too.

**Comment by maxsupermanhd** [comment]
So, for some reason mvn did not wanted to work on newer java version so I just disabled tests and it was fine...
