### ISSUE TITLE
Handle SRV records

### ISSUE THREAD

**Issue by mircokroon** [mircokroon/minecraft-world-downloader#31]
Minecraft servers can use (DNS) SRV records for redirects. E.g. when a user connects to `example.com`, Minecraft usually checks for SRV records at `_minecraft._tcp.example.com`. If such a record exists, the URL given there should be connected to instead of the given domain.

Currently these records are ignored by the world downloader.

**Comment by ChillerDragon** [comment]
Oh nice I also run into this issue but I got it solved.

My domain zillyhuhn.com is pointing to ip A
and _minecraft._tcp.zillyhuhn.com is pointing to ip B.

If I launch minecraft and connect to zillyhuhn.com I get connected to ip B.
If I launch world downloader pointing at zillyhuhn.com I get connected to ip A.
But the fix is pointing the world downloader at lgl.zillyhuhn.com which also connects to ip B.

![image](https://user-images.githubusercontent.com/20344300/85992116-b9e25c80-b9f4-11ea-89c4-567501fe0a5c.png)


Also feel free to test it on my server if you need a srv record sample server.

**Comment by mircokroon** [comment]
Yeah, seeing as it's fairly easy to get around I don't really consider it to be a very high priority. But it'd be nice to get it done at some point.

**Comment by ChillerDragon** [comment]
@mircokroon any idea how to get around on 2b2t.org seems like connecting via IP does not work.
![image](https://user-images.githubusercontent.com/20344300/93324176-d59c1880-f815-11ea-898b-2169565cedfe.png)

**Comment by ChillerDragon** [comment]
nvm was the auth issue idk whats going on
