### ISSUE TITLE
It does not start

### ISSUE THREAD

**Issue by Wauzie** [mircokroon/minecraft-world-downloader#328]
Hello 
I have downloaded the downloader for 1.18.1 and tried to run it but it doesn't work even when I tell windows to run it no GUI comes up.
I have turned off my antivirus Bitdefender.

I have downloaded the .exe 

ps also other versions did not work and java should be correct because everything else works.

if you need anything else to help just say what :)
thank you <3

**Comment by mircokroon** [comment]
This might be fixed in v1.16 although I'm not sure if it was the same issue you were dealing with

**Comment by monkeysHK** [comment]
Hello. I had the same issue. After the downloader crashed once, the EXE did not run for me. And when I tried the command line method it says "config.Config.instance is null". Trying to remove the "world" and "cache" folders would work. (When I checked, config.json was empty.)

Still would be nice if it gives user an error when it crashed this way, since the EXE simply does not respond whatsoever.

**Comment by mircokroon** [comment]
Ahh so I guess it just doesn't handle empty config files correctly, thanks!
