### ISSUE TITLE
Horrible Lag after long use, massive level.dat file

### ISSUE THREAD

**Issue by leumasme** [mircokroon/minecraft-world-downloader#34]
After using this project for a few days, it has become practically unusable.
Connecting to the server feels as if under heavy connection lag when connecting via the proxy (It works fine without the proxy).
After checking the saved world, i immediately noticed that the level.dat is over 11mb big - way bigger than normal.
Trying to open it in NBTExplorer does not show more or bigger entries than expected.
Note that i left the Proxy Application running when leaving the server and putting my PC to sleep mode over night, as i wanted to keep the preview of the already loaded world, not sure if this is a part of the problem.
The World File would probably help you fix this - if you need it, please give me a way to contact you privately as i would prefer to not make the world file public.

**Comment by mircokroon** [comment]
Hmm that's strange, my best guess is that the player's position in the `level.dat` is being duplicated every time the world is saved instead of being overwritten, and this is hidden by NBTExplorer somehow.

If you could send me the `level.dat` file I can investigate that.

You can right-click on the map once you are connected and pick 'Load all existing chunks', this way it will load back all the data that was previously saved. This way you don't have to keep it running. I'd suggest deleting/renaming the `level.dat` to see if that helps reduce some of the lag, if it has to read/write that large of a file every time I can definitely imagine that causing some lag issuees.

If you'd like to investigate a little bit more you could try running a profiler on the application to see if there is any out-of-the-ordinary CPU/memory usage going on.

**Comment by leumasme** [comment]
@mircokroon Whoops, seems like i made a draft of the email but didn't send it, my bad. Sent it now.

**Comment by mircokroon** [comment]
No problem. 

It seems to indeed be related to duplicate tags in the `level.dat` file. There's not really a super quick fix for it (it's an issue in a library). I've circumvented the issue now by always creating a new `level.dat` file instead of trying to update the existing one in [release 1.5.3](https://github.com/mircokroon/minecraft-world-downloader/releases/tag/v1.5.3).

Fun fact: the `level.dat` is a compressed format, uncompressed your `level.dat` file was 436 MB.

**Comment by ImUrX** [comment]
close?

**Comment by ImUrX** [comment]
oh i must say, the cirumvention of the issue should be removed, it seems this has been fixed in the library that is being used llbit/jo-nbt#1

**Comment by mircokroon** [comment]
I'm aware of that, but we can't easily update to that version as it's not on Maven (yet, hopefully). I'll close this once I can verify it works well with that.

**Comment by mircokroon** [comment]
I guess that's never going to happen, I included the latest version differently now, so this has been resolved
