### ISSUE TITLE
Set ram on exe?

### ISSUE THREAD

**Issue by Xetaxheb** [mircokroon/minecraft-world-downloader#430]
Is there a way to set the ram usage on the exe? Can there be?

**Comment by MCFX2** [comment]
for what purpose?

**Comment by ZandercraftGames** [comment]
I think also a certain amount of culling of data is needed once it gets saved to the disk. The program progressively takes up more and more memory until it hits whatever limit you've set for Java and then it locks up due to running out of memory.

Maybe something like dumping the data out of memory once it's stored to the disk and only keeping the area surrounding the player loaded. Leave the render on the screen, but don't occupy memory with the entire world's data.

**Comment by rautamiekka** [comment]
That shoulda already been done, if not to such an extreme extent.

**Comment by ZandercraftGames** [comment]
> That shoulda already been done, if not to such an extreme extent.

Evidently not. The longer I'm in the world and the more I explore, the more RAM usage of the program increases until it hits ~6GB (what I've assigned it) on the jar or ~2-3GB on the EXE and then it starts throwing out-of-memory errors and stops responding. 
Clearly it's either not managing memory properly and leaking it, or it's just occupying memory with all of the world's data and not cleaning itself up. It doesn't seem to matter what I allocate either. It will eventually use it all (I've even tested up to 10GB).
