### ISSUE TITLE
Make not loaded Chunks generate?

### ISSUE THREAD

**Issue by OfflinePing** [mircokroon/minecraft-world-downloader#469]
Hey,
So I downloaded a World with the most Important Chunks and now I want to let the other Chunks get generated by Minecraft (with the same seed). But if I just load the world it has these cuts in the world and it just doesnt load chunks there. How do I fix that?

**Comment by Felina-Lain** [comment]
Could the server world have been created with a previous version of minecraft, and then upgraded over time, so now when you download it for recent version, the generation with seed is wrong because it's not the version it was originally generated in?
(Not part of this project, just was looking on the issues for infos, and saw this, and thought of that suggestion)
