### ISSUE TITLE
Trojan.WinGo.Reverseshell is worlddownloader a virus?

### ISSUE THREAD

**Issue by loubexos** [mircokroon/minecraft-world-downloader#704]
**Describe the bug**
When I scan worlddownloader.exe with virustotal, virustotal thinks it is a virus, is that true?
**Steps to reproduce**
Scann world-downloader-launcher.exe with VirusTotal

**Screenshots**
![Screenshot 2024-10-27 133101](https://github.com/user-attachments/assets/d4817e8a-9be4-4c55-8363-5d34e2be9d31)

**Version**
 - Game: Minecraft 1.21.1
 - Downloader: latest
 - Launcher (if login issues): 14.2

**Comment by PixelCattt** [comment]
By connecting to the server through localhost, the mod essentially intercepts and reroutes Minecraft traffic before it reaches the server. This setup would allow it to control or modify how certain data is processed. Because of this rerouting, the antivirus could think it is trying to open a reverse shell so somebody could modify or steal the data you send to and receive from the server.

**Comment by loubexos** [comment]
Okay, I guess that's good then, thanks!

> By connecting to the server through localhost, the mod essentially intercepts and reroutes Minecraft traffic before it reaches the server. This setup would allow it to control or modify how certain data is processed. Because of this rerouting, the antivirus could think it is trying to open a reverse shell so somebody could modify or steal the data you send to and receive from the server.
