### ISSUE TITLE
Fails to draw all chunks.

### ISSUE THREAD

**Issue by Esper89** [mircokroon/minecraft-world-downloader#96]
When I click "Draw all existing chunks" while connected to the server, only some of the chunks are drawn. The chunks that are not drawn are randomly distributed throughout the entire world. Upon clicking "Draw all existing chunks" again, some of those chunks will be drawn, and others will remain not draw. See below for saved overviews.

After running once:
![rendered](https://user-images.githubusercontent.com/69338029/103387361-44556700-4ad1-11eb-90ad-3a5039979d56.png)

After running twice:
![rendered](https://user-images.githubusercontent.com/69338029/103387365-49b2b180-4ad1-11eb-8619-00c670efc26e.png)

An error message also appears in stderr each time, with only the first message having a full explanation. 

[Stdout and Stderr](https://github.com/mircokroon/minecraft-world-downloader/files/5756083/stdout%2Bstderr.txt)

This only started happening recently, leading me to believe it is the world file that caused it. The world was exclusively created with the downloader, and has not been modified by anything else.

[World File](https://envl.app/esper8989/1uyRRa!PtUfWX1qNhEB0s1g)

**Comment by mircokroon** [comment]
Well that's strange, I'll check it out. Which Minecraft version is this?

**Comment by Esper89** [comment]
Minecraft 1.16.4, with the fabric loader and the fabric API installed.

**Comment by mircokroon** [comment]
Sorry it took a while. 

It turns out the issue was in the code for the transparency of water. If water is found it will sample up to 24 blocks deep looking for other blocks, and if the water flowed into the void within 24 blocks it would try to sample the blocks at negative coordinates. The reason that this lead to the sporadic loading of chunks is that chunks are loaded in a random order, and it would stop once it encountered one of those coordinates with the water.

Example of one such case:
![image](https://user-images.githubusercontent.com/23699979/106361401-fde86780-631d-11eb-96c0-9bde9e04d32a.png)

Will be fixed in an upcoming version by not sampling < 0 and by catching errors per chunk.
